cluster.name: ${CLUSTER_NAME}

node:
  name: ${NODE_NAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

discovery.zen:
  minimum_master_nodes: ${MINIMUM_MASTER_NODES}
  ping.unicast.hosts: ${HOSTS}
network.host: ${NETWORK_HOST}

http:
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

searchguard.ssl.transport.keystore_filepath: certs/${NODE_NAME}-keystore.jks
searchguard.ssl.transport.keystore_password: ${KS_PWD} 
searchguard.ssl.transport.truststore_filepath: certs/truststore.jks 
searchguard.ssl.transport.truststore_password: ${TS_PWD} 
searchguard.ssl.transport.enforce_hostname_verification: false 
searchguard.ssl.http.enabled: true 
searchguard.ssl.http.keystore_filepath: certs/${NODE_NAME}-keystore.jks 
searchguard.ssl.http.keystore_password: ${KS_PWD} 
searchguard.ssl.http.truststore_filepath: certs/truststore.jks 
searchguard.ssl.http.truststore_password: ${TS_PWD} 
searchguard.authcz.admin_dn:                                 
  - CN=sgadmin   
